language: node_js
sudo: false
node_js:
    - stable
    - 7
script:
    - npm test
    - npm run compile
after_success:
    - 'curl -Lo travis_after_all.py https://git.io/travis_after_all'
    - python travis_after_all.py
    - 'export $(cat .to_export_back) &> /dev/null'
    - npm run coveralls
    - npm run semantic-release

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
